/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDaysProgressBar {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppInfoBanner {
    }
    interface AppMenu {
    }
    interface AppProgressBar {
        "reCalculateProgress": () => Promise<void>;
        "results": any;
    }
    interface AppRoot {
    }
    interface AppSubmitBanner {
    }
    interface AppVotingBox {
        "data": any;
    }
    interface AppVotingBoxSample {
    }
}
declare global {
    interface HTMLAppDaysProgressBarElement extends Components.AppDaysProgressBar, HTMLStencilElement {
    }
    var HTMLAppDaysProgressBarElement: {
        prototype: HTMLAppDaysProgressBarElement;
        new (): HTMLAppDaysProgressBarElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppInfoBannerElement extends Components.AppInfoBanner, HTMLStencilElement {
    }
    var HTMLAppInfoBannerElement: {
        prototype: HTMLAppInfoBannerElement;
        new (): HTMLAppInfoBannerElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProgressBarElement extends Components.AppProgressBar, HTMLStencilElement {
    }
    var HTMLAppProgressBarElement: {
        prototype: HTMLAppProgressBarElement;
        new (): HTMLAppProgressBarElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSubmitBannerElement extends Components.AppSubmitBanner, HTMLStencilElement {
    }
    var HTMLAppSubmitBannerElement: {
        prototype: HTMLAppSubmitBannerElement;
        new (): HTMLAppSubmitBannerElement;
    };
    interface HTMLAppVotingBoxElement extends Components.AppVotingBox, HTMLStencilElement {
    }
    var HTMLAppVotingBoxElement: {
        prototype: HTMLAppVotingBoxElement;
        new (): HTMLAppVotingBoxElement;
    };
    interface HTMLAppVotingBoxSampleElement extends Components.AppVotingBoxSample, HTMLStencilElement {
    }
    var HTMLAppVotingBoxSampleElement: {
        prototype: HTMLAppVotingBoxSampleElement;
        new (): HTMLAppVotingBoxSampleElement;
    };
    interface HTMLElementTagNameMap {
        "app-days-progress-bar": HTMLAppDaysProgressBarElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-info-banner": HTMLAppInfoBannerElement;
        "app-menu": HTMLAppMenuElement;
        "app-progress-bar": HTMLAppProgressBarElement;
        "app-root": HTMLAppRootElement;
        "app-submit-banner": HTMLAppSubmitBannerElement;
        "app-voting-box": HTMLAppVotingBoxElement;
        "app-voting-box-sample": HTMLAppVotingBoxSampleElement;
    }
}
declare namespace LocalJSX {
    interface AppDaysProgressBar {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppInfoBanner {
    }
    interface AppMenu {
    }
    interface AppProgressBar {
        "results"?: any;
    }
    interface AppRoot {
    }
    interface AppSubmitBanner {
    }
    interface AppVotingBox {
        "data"?: any;
    }
    interface AppVotingBoxSample {
    }
    interface IntrinsicElements {
        "app-days-progress-bar": AppDaysProgressBar;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-info-banner": AppInfoBanner;
        "app-menu": AppMenu;
        "app-progress-bar": AppProgressBar;
        "app-root": AppRoot;
        "app-submit-banner": AppSubmitBanner;
        "app-voting-box": AppVotingBox;
        "app-voting-box-sample": AppVotingBoxSample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-days-progress-bar": LocalJSX.AppDaysProgressBar & JSXBase.HTMLAttributes<HTMLAppDaysProgressBarElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-info-banner": LocalJSX.AppInfoBanner & JSXBase.HTMLAttributes<HTMLAppInfoBannerElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-progress-bar": LocalJSX.AppProgressBar & JSXBase.HTMLAttributes<HTMLAppProgressBarElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-submit-banner": LocalJSX.AppSubmitBanner & JSXBase.HTMLAttributes<HTMLAppSubmitBannerElement>;
            "app-voting-box": LocalJSX.AppVotingBox & JSXBase.HTMLAttributes<HTMLAppVotingBoxElement>;
            "app-voting-box-sample": LocalJSX.AppVotingBoxSample & JSXBase.HTMLAttributes<HTMLAppVotingBoxSampleElement>;
        }
    }
}
